import { Position } from "@xyflow/svelte"

import { Graph, type Edge, type Node, type Orientation } from "$lib/types"
import { positionNodes } from "$lib/layout"

const name = "First"
const orientation: Orientation = "vertical"
const graph = { name, orientation }
const description = { content: null }
const position = { x: 0, y: 0 }
const width = 100
const height = 50
const targetPosition = Position.Top
const sourcePosition = Position.Bottom

const baseNodes: Node[] = [
  //  {
  //   id: "skillet",
  //     type: "group",
  //     data: {},

  // },
  {
    id: "ground-beef",
    type: "material",
    data: {
      label: "Ground Beef",
      quantity: { amount: 10, unit: "lb" },
      graph,
      description,
    },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "chili-powder",
    type: "material",
    data: {
      label: "Chili Powder",
      quantity: { amount: 10, unit: "lb" },
      graph,
      description,
    },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "cumin",
    type: "material",
    data: {
      label: "Cumin",
      quantity: { amount: 10, unit: "lb" },
      graph,
      description,
    },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "oregano",
    type: "material",
    data: {
      label: "Oregano",
      quantity: { amount: 10, unit: "lb" },
      graph,
      description,
    },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "garlic-powder",
    type: "material",
    data: {
      label: "Garlic Powder",
      quantity: { amount: 10, unit: "lb" },
      graph,
      description,
    },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "salt",
    type: "material",
    data: {
      label: "Salt",
      quantity: { amount: 10, unit: "lb" },
      graph,
      description,
    },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "black-pepper",
    type: "material",
    data: {
      label: "Black Pepper",
      quantity: { amount: 10, unit: "lb" },
      graph,
      description,
    },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "tomato-paste",
    type: "material",
    data: {
      label: "Tomato Paste",
      quantity: { amount: 10, unit: "lb" },
      graph,
      description,
    },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "water",
    type: "material",
    data: {
      label: "Water",
      quantity: { amount: 10, unit: "lb" },
      graph,
      description,
    },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "olive-oil",
    type: "material",
    data: {
      label: "Olive Oil",
      quantity: { amount: 10, unit: "lb" },
      graph,
      description,
    },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "flour-tortillas",
    type: "material",
    data: {
      label: "Flour Tortillas",
      quantity: { amount: 10, unit: "lb" },
      graph,
      description,
    },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "lettuce",
    type: "material",
    data: {
      label: "Lettuce",
      quantity: { amount: 10, unit: "lb" },
      graph,
      description,
    },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "shredded-cheese",
    type: "material",
    data: {
      label: "Shredded Cheese",
      quantity: { amount: 10, unit: "lb" },
      graph,
      description,
    },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "tomatoes",
    type: "material",
    data: {
      label: "Tomatoes",
      quantity: { amount: 10, unit: "lb" },
      graph,
      description,
    },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "red-onion",
    type: "material",
    data: {
      label: "Red Onion",
      quantity: { amount: 10, unit: "lb" },
      graph,
      description,
    },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "sour-cream",
    type: "material",
    data: {
      label: "Sour Cream",
      quantity: { amount: 10, unit: "lb" },
      graph,
      description,
    },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "guacamole",
    type: "material",
    data: {
      label: "Guacamole",
      quantity: { amount: 10, unit: "lb" },
      graph,
      description,
    },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "heat",
    type: "step",
    data: { label: "heat", level: "medium-high", graph, description },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
    // parentId: "skillet",
  },
  {
    id: "brown",
    data: { label: "brown", graph, description },
    type: "step",
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
    // parentId: "skillet",
  },
  {
    id: "drain",
    data: { label: "drain", graph, description },
    type: "step",
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
    // parentId: "skillet",
  },
  {
    id: "warm",
    data: { label: "warm", graph, description },
    type: "step",
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "season",
    data: { label: "season", graph, description },
    type: "step",
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
    // parentId: "skillet",
  },
  {
    id: "plate",
    data: { label: "plate", graph, description },
    type: "step",
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "hot-oil",
    data: { label: "hot-oil", graph, description },
    // parentId: "skillet",
    type: "material",
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "browned-beef",
    data: { label: "browned-beef", graph, description },
    // parentId: "skillet",
    type: "material",
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "drained-browned-beef",
    data: { label: "drained-browned-beef", graph, description },
    // parentId: "skillet",
    type: "material",
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "warm-tortillas",
    data: { label: "warm-tortillas", graph, description },
    type: "material",
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "seasoned-beef",
    data: { label: "seasoned-beef", graph, description },
    type: "material",
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
    // parentId: "skillet",
  },
  {
    id: "fat",
    type: "material",
    data: { label: "fat", graph, description },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
  {
    id: "taco",
    type: "material",
    data: { label: "taco", graph, description },
    position,
    width,
    height,
    targetPosition,
    sourcePosition,
  },
]

const type = "smoothstep"
const animated = true
const baseEdges: Edge[] = [
  {
    id: "1",
    source: "olive-oil",
    target: "heat",
    type,
    animated,
    data: { graph: { name }, quantity: { amount: 1, unit: "tbsp" } },
  },
  {
    id: "2",
    source: "ground-beef",
    target: "brown",
    type,
    animated,
    data: { graph: { name }, quantity: { amount: 1, unit: "lb" } },
  },
  { id: "3", source: "heat", target: "hot-oil", type, animated, data: { graph: { name } } },
  { id: "4", source: "hot-oil", target: "brown", type, animated, data: { graph: { name } } },
  {
    id: "5",
    source: "brown",
    target: "browned-beef",
    type,
    animated,
    data: { graph: { name }, time: { amount: 7, unit: "min" } },
  },
  { id: "6", source: "browned-beef", target: "drain", type, animated, data: { graph: { name } } },
  { id: "7", source: "drain", target: "drained-browned-beef", type, animated, data: { graph: { name } } },
  { id: "8", source: "drain", target: "fat", type, animated, data: { graph: { name } } },
  { id: "9", source: "drained-browned-beef", target: "season", type, animated, data: { graph: { name } } },
  {
    id: "10",
    source: "chili-powder",
    target: "season",
    type,
    animated,
    data: { graph: { name }, quantity: { amount: 2, unit: "tsp" } },
  },
  {
    id: "11",
    source: "cumin",
    target: "season",
    type,
    animated,
    data: { graph: { name }, quantity: { amount: 2, unit: "tsp" } },
  },
  {
    id: "12",
    source: "oregano",
    target: "season",
    type,
    animated,
    data: { graph: { name }, quantity: { amount: 0.5, unit: "tsp" } },
  },
  {
    id: "13",
    source: "garlic-powder",
    target: "season",
    type,
    animated,
    data: { graph: { name }, quantity: { amount: 0.5, unit: "tsp" } },
  },
  {
    id: "14",
    source: "salt",
    target: "season",
    type,
    animated,
    data: { graph: { name }, quantity: { amount: 0.5, unit: "tsp" } },
  },
  {
    id: "15",
    source: "black-pepper",
    target: "season",
    type,
    animated,
    data: { graph: { name }, quantity: { amount: 0.5, unit: "tsp" } },
  },
  {
    id: "16",
    source: "tomato-paste",
    target: "season",
    type,
    animated,
    data: { graph: { name }, quantity: { amount: 2, unit: "tbsp" } },
  },
  {
    id: "17",
    source: "water",
    target: "season",
    type,
    animated,
    data: { graph: { name }, quantity: { amount: 0.5, unit: "cup" } },
  },
  {
    id: "18",
    source: "flour-tortillas",
    target: "warm",
    type,
    animated,
    data: { graph: { name }, quantity: { amount: 8, unit: "unit" } },
  },
  { id: "19", source: "warm", target: "warm-tortillas", type, animated, data: { graph: { name } } },
  { id: "20", source: "warm-tortillas", target: "plate", type, animated, data: { graph: { name } } },
  { id: "21", source: "lettuce", target: "plate", type, animated, data: { graph: { name } } },
  { id: "22", source: "shredded-cheese", target: "plate", type, animated, data: { graph: { name } } },
  { id: "23", source: "tomatoes", target: "plate", type, animated, data: { graph: { name } } },
  { id: "24", source: "red-onion", target: "plate", type, animated, data: { graph: { name } } },
  { id: "25", source: "sour-cream", target: "plate", type, animated, data: { graph: { name } } },
  { id: "26", source: "guacamole", target: "plate", type, animated, data: { graph: { name } } },
  { id: "27", source: "season", target: "seasoned-beef", type, animated, data: { graph: { name } } },
  { id: "28", source: "seasoned-beef", target: "plate", type, animated, data: { graph: { name } } },
  { id: "29", source: "plate", target: "taco", type, animated, data: { graph: { name } } },
]

const { nodes, edges } = await positionNodes(baseNodes, baseEdges)
export default new Graph({ name, nodes, edges })
